codegeex2 = "/disk/Yuchen/HF/models/codegeex2"
codegen = "/disk/Yuchen/HF/models/codeGen"
codet5 = "/disk/Yuchen/HF/models/codeT5"
codet5p = "/disk/Yuchen/HF/models/codet5p"
chatglm = "/disk/Yuchen/HF/models/chatglm-3"
scd = "/disk/Yuchen/HF/models/SCD"
codegemma2b = "/disk/Yuchen/HF/models/codegemma-2b"
codegemma7b = "/disk/Yuchen/HF/models/codegemma-7b"
codellama = "/disk/Yuchen/HF/models/codellama-7b"
gemma_2b = "/disk/Yuchen/HF/models/gemma-2b"
gemma2_2b_it = "/disk/Yuchen/HF/models/gemma2-2b-it"
tinyllama = "/disk/Yuchen/HF/models/TinyLlama-1.1B-Chat-v1.0"
llama32 = "/disk/Yuchen/HF/models/llama-3.2-1B-IT"
deepseek_d_qwen = "/disk/Yuchen/HF/models/deepseek-r1-distilled-qwen-1.5b"
llama_chat = "/disk/Yuchen/HF/models/llama-chat"
bert = "/disk/Yuchen/HF/models/bert"

manual = "/disk/Yuchen/HF/data/manual"